# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: um-book_development
  pool: 5
  timeout: 5000
  username: um-book
  password: um-book
  host: 127.0.0.1
